gem:
  all: false
  exclude:
    # annotated
    # - activemodel
    # annotated
    # - activerecord
    # annotated
    # - activesupport
    # - ansi
    - ast
    - binding_of_caller
    - builder
    - byebug
    - coderay
    - commander
    # - concurrent-ruby
    # - csv
    - debug_inspector
    - diff-lcs
    - erubi
    # - fileutils
    - ffi
    - highline
    - i18n
    - interception
    - language_server-protocol
    - listen
    - method_source
    # - minitest-power_assert
    # - minitest
    - netrc
    - parallel
    - parlour
    - parser
    # - pg
    # - power_assert
    - prettier_print
    - pry-byebug
    - pry-rescue
    - pry-stack_explorer
    - pry
    - racc
    - rainbow
    - rake
    - rbi
    - rbs
    - rb-fsevent
    - rb-inotify
    - ruby-progressbar
    - sord
    - spoom
    - steep
    - strscan
    - syntax_tree
    - tapioca
    - terminal-table
    - thor
    - tzinfo
    - unicode-display_width
    - unparser
    - webrick
    - yard-sorbet
    - yard
  doc: true
  workers: 8
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
